# Netlify configuration for Next.js app in turbo monorepo
[build]
  base      = "apps/ui"
  command   = "pnpm install && pnpm run build"
  publish   = ".next"
  functions = ".netlify/functions"
  ignore    = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ."

# Environment variables
[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9.15.2"

[[plugins]]
  package = "@netlify/plugin-nextjs@5.11.2"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"