[build]
  command = "pnpm install && pnpm run build && cd apps/ui"
  
  publish = "apps/ui/.next"

[build.environment]
  NODE_VERSION = "20.3.0"
  # NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_ENABLED = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_SHARP_PATH = "/opt/buildhome/.npm-global/lib/node_modules/sharp"
  
  # Optimize Next.js build
  NEXT_IGNORE_BUILD_STATIC_ERRORS = "1"
  NEXT_IGNORE_TYPECHECK_ERRORS = "1"
  NEXT_IGNORE_LINT_ERRORS = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true