# Netlify configuration for Next.js app
[build]
  command   = "pnpm run build"
  publish   = "apps/ui/.next"
  functions = "apps/ui/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/"
type = "rewrite"