[build]
  command = "pnpm install && pnpm run build && cd apps/ui"
  publish = "apps/ui/.next"

[build.environment]
  # NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  