[build]
  base = "/"
  command = "pnpm install --frozen-lockfile && pnpm turbo run build --filter=zzyra-web3-automation"
  publish = "apps/ui/.next"

[build.environment]
  NODE_VERSION = "20.3.0"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_ENABLED = "false"
  
  # Critical memory optimization - reduced from 8192 to 3072
  NODE_OPTIONS = "--max-old-space-size=3072 --optimize-for-size"
  
  # Next.js specific optimizations
  NEXT_SHARP_PATH = "/opt/buildhome/.npm-global/lib/node_modules/sharp"
  NEXT_IGNORE_BUILD_STATIC_ERRORS = "1"
  NEXT_IGNORE_TYPECHECK_ERRORS = "1"
  NEXT_IGNORE_LINT_ERRORS = "1"
  
  # Turborepo optimizations
  TURBO_TELEMETRY_DISABLED = "1"
  TURBO_CACHE_DIR = ".turbo"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optimize build performance
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Remove the problematic build.ignore section
# [build.ignore]
#   command = "bash -c 'git diff --quiet HEAD^ HEAD -- apps/ui/ packages/types/ packages/database/ || exit 0'"