[build]
  command = "pnpm install && pnpm run build && cd apps/ui"
  publish = "apps/ui/.next"

[build.environment]
  NODE_VERSION = "20.3.0"
  # NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  