/**
 * Defines all available block types for the workflow system
 * This serves as the single source of truth for block types
 */
export enum BlockType {
  // Trigger blocks
  PRICE_MONITOR = "PRICE_MONITOR",
  SCHEDULE = "SCHEDULE",
  WEBHOOK = "WEBHOOK",

  // Action blocks
  EMAIL = "EMAIL",
  NOTIFICATION = "NOTIFICATION",
  TRANSFORM = "TRANSFORM",
  WALLET = "WALLET",
  TRANSACTION = "TRANSACTION",
  DATABASE = "DATABASE",
  DISCORD = "DISCORD",
  LLM_PROMPT = "LLM_PROMPT",
  API = "API",
  SMS = "SMS",
  AI = "AI",
  FINANCE = "FINANCE",

  // Logic blocks
  CONDITION = "CONDITION",
  DELAY = "DELAY",

  // Finance blocks
  DEFI_PRICE_MONITOR = "DEFI_PRICE_MONITOR",
  DEFI_YIELD_MONITOR = "DEFI_YIELD_MONITOR",
  DEFI_PORTFOLIO = "DEFI_PORTFOLIO",
  DEFI_REBALANCE = "DEFI_REBALANCE",
  DEFI_SWAP = "DEFI_SWAP",
  DEFI_GAS = "DEFI_GAS",
  DEFI_PROTOCOL = "DEFI_PROTOCOL",
  DEFI_YIELD_STRATEGY = "DEFI_YIELD_STRATEGY",
  DEFI_LIQUIDITY = "DEFI_LIQUIDITY",
  DEFI_POSITION = "DEFI_POSITION",
  AI_BLOCKCHAIN = "AI_BLOCKCHAIN",

  // Advanced monitoring
  PROTOCOL_MONITOR = "PROTOCOL_MONITOR",
  POSITION_MANAGER = "POSITION_MANAGER",
  YIELD_STRATEGY = "YIELD_STRATEGY",
  LIQUIDITY_PROVIDER = "LIQUIDITY_PROVIDER",
  REBALANCE_CALCULATOR = "REBALANCE_CALCULATOR",
  GAS_OPTIMIZER = "GAS_OPTIMIZER",
  SWAP_EXECUTOR = "SWAP_EXECUTOR",
  PORTFOLIO_BALANCE = "PORTFOLIO_BALANCE",
  YIELD_MONITOR = "YIELD_MONITOR",

  // Custom blocks
  CUSTOM = "CUSTOM",
  GOAT_FINANCE = "GOAT_FINANCE",

  // Default/fallback
  UNKNOWN = "UNKNOWN",
}
