name: Dev CI/CD
on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"
  workflow_dispatch:

env:
  CI: false

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get short SHA and short Run ID
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "run_id_short=${GITHUB_RUN_ID: -4}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # API Image
      - name: build && push API
        id: build-push-api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            argahv/zzyra:api-dev
            argahv/zzyra:api-dev-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.run_id_short }}

    # Worker Image
      - name: build && push Worker
        id: build-push-worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.zzyra-worker
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            argahv/zzyra:zzyra-worker-dev
            argahv/zzyra:zzyra-worker-dev-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.run_id_short }}

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      run_id_short: ${{ steps.vars.outputs.run_id_short }}